+iris support to freeze/thaw scripts

diff --git a/files/localbin/freeze_all_cache_instances b/files/localbin/freeze_all_cache_instances
--- a/files/localbin/freeze_all_cache_instances
+++ b/files/localbin/freeze_all_cache_instances
@@ -3,19 +3,41 @@ set noclobber
 
 date
 fail=''
-for inst in $(ccontrol qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
-  if [[ -f "/epic/$inst/bin/instfreeze" ]]; then
-    "/epic/$inst/bin/instfreeze"
-    if [[ $? -ne 0 ]]; then
-      echo "$inst failed to freeze"
+
+if [[ which ccontrol &> /dev/null ]; then
+  for inst in $(ccontrol qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
+    if [[ -f "/epic/$inst/bin/instfreeze" ]]; then
+      "/epic/$inst/bin/instfreeze"
+      if [[ $? -ne 0 ]]; then
+        echo "$inst failed to freeze"
+        fail+="$inst "
+      fi
+    else
+      echo "Can't find instfreeze for $inst"
       fail+="$inst "
     fi
-  else
-    echo "Can't find instfreeze for $inst"
-    fail+="$inst "
+  done
+  if [[ $fail -ne '' ]];then
+    echo "$fail"
   fi
-done
-if [[ $fail -ne '' ]];then
-  echo "$fail"
 fi
+
+if [[ which iris &> /dev/null ]; then
+  for inst in $(iris qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
+    if [[ -f "/epic/$inst/bin/instfreeze" ]]; then
+      "/epic/$inst/bin/instfreeze"
+      if [[ $? -ne 0 ]]; then
+        echo "$inst failed to freeze"
+        fail+="$inst "
+      fi
+    else
+      echo "Can't find instfreeze for $inst"
+      fail+="$inst "
+    fi
+  done
+  if [[ $fail -ne '' ]];then
+    echo "$fail"
+  fi
+fi
+
 date
diff --git a/files/localbin/thaw_all_cache_instances b/files/localbin/thaw_all_cache_instances
--- a/files/localbin/thaw_all_cache_instances
+++ b/files/localbin/thaw_all_cache_instances
@@ -3,19 +3,41 @@ set noclobber
 
 date
 fail=''
-for inst in $(ccontrol qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
-  if [[ -f "/epic/$inst/bin/instthaw" ]]; then
-    "/epic/$inst/bin/instthaw"
-    if [[ $? -ne 0 ]]; then
-      echo "$inst failed to thaw"
+
+if [[ which ccontrol &> /dev/null ]; then
+  for inst in $(ccontrol qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
+    if [[ -f "/epic/$inst/bin/instthaw" ]]; then
+      "/epic/$inst/bin/instthaw"
+      if [[ $? -ne 0 ]]; then
+        echo "$inst failed to thaw"
+        fail+="$inst "
+      fi
+    else
+      echo "Can't find instthaw for $inst"
       fail+="$inst "
     fi
-  else
-    echo "Can't find instthaw for $inst"
-    fail+="$inst "
+  done
+  if [[ $fail -ne '' ]]; then
+    echo $fail
   fi
-done
-if [[ $fail -ne '' ]]; then
-  echo $fail
 fi
+
+if [[ which iris &> /dev/null ]; then
+  for inst in $(iris qlist | grep running | cut -d '^' -f 1 | tr [:upper:] [:lower:]); do
+    if [[ -f "/epic/$inst/bin/instthaw" ]]; then
+      "/epic/$inst/bin/instthaw"
+      if [[ $? -ne 0 ]]; then
+        echo "$inst failed to thaw"
+        fail+="$inst "
+      fi
+    else
+      echo "Can't find instthaw for $inst"
+      fail+="$inst "
+    fi
+  done
+  if [[ $fail -ne '' ]]; then
+    echo $fail
+  fi
+fi
+
 date
